# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: txt
email: clinton.ngyn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  stories
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://txt.clinton.so" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: clinton_ngn
github_username:  clintonn

# assets

assets:
  compress:
    css: default
    js: default
  autowrite: true
  cache: .asset-cache
  cache_type: filesystem
  prefix: "/assets"
  digest: true
  assets:
    - "*.png"
    - "bundle.css"
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js
  features:
    liquid: true
    integrity: default
    # This will add height and width attributes for an img tag.
    automatic_img_size: default
    # This will add the digest path as an alt attribute for an img tag.
    automatic_img_alt : false

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-assets

exclude:
  - Gemfile
  - Gemfile.lock
